# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-29 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='第一个名字')),
                ('last_name', models.CharField(max_length=20, verbose_name='姓')),
                ('emaill', models.CharField(max_length=50, verbose_name='邮箱')),
                ('user_name', models.CharField(max_length=30, verbose_name='用户名')),
                ('password', models.CharField(max_length=20, verbose_name='密码')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
        ),
    ]
