# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-01 15:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='器材名字')),
                ('cover', models.ImageField(upload_to='static/images', verbose_name='器材图片')),
            ],
            options={
                'verbose_name_plural': '器材关于我们',
                'verbose_name': '器材关于我们',
            },
        ),
        migrations.CreateModel(
            name='About_z',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='标题')),
                ('cover', models.ImageField(upload_to='static/images', verbose_name='图片')),
                ('contest', models.TextField(verbose_name='介绍')),
            ],
            options={
                'verbose_name_plural': '关于我们的主页面',
                'verbose_name': '关于我们的主页面',
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('cover', models.ImageField(upload_to='static/images/banner', verbose_name='轮播图')),
                ('link_url', models.URLField(max_length=100, verbose_name='图片链接')),
                ('idx', models.IntegerField(verbose_name='索引')),
                ('is_active', models.BooleanField(default=False, verbose_name='是否是active')),
            ],
            options={
                'verbose_name_plural': '轮播图',
                'verbose_name': '轮播图',
            },
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=30, verbose_name='标题')),
                ('c_cover', models.ImageField(upload_to='static/images', verbose_name='封面')),
                ('c_contest', models.TextField(verbose_name='内容')),
                ('c_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='时间')),
            ],
            options={
                'verbose_name_plural': '新闻',
                'verbose_name': '新闻',
            },
        ),
        migrations.CreateModel(
            name='Knowledge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='标题')),
                ('contest', models.TextField(verbose_name='内容')),
                ('date', models.DateField(verbose_name='日期')),
            ],
            options={
                'verbose_name_plural': '保护环境(健康)',
                'verbose_name': '保护环境(健康)',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, verbose_name='姓名')),
                ('tel', models.CharField(max_length=11, verbose_name='电话')),
                ('email', models.CharField(max_length=30, verbose_name='邮箱')),
                ('content', models.CharField(max_length=500, verbose_name='内容')),
            ],
            options={
                'verbose_name_plural': '在线留言',
                'verbose_name': '在线留言',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='工程名字')),
                ('cover', models.ImageField(upload_to='static/images', verbose_name='图片')),
                ('contest', models.TextField(verbose_name='介绍')),
            ],
            options={
                'verbose_name_plural': '工程案例',
                'verbose_name': '工程案例',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20, verbose_name='名字')),
                ('post', models.CharField(max_length=20, verbose_name='岗位')),
                ('cover', models.ImageField(upload_to='', verbose_name='头像')),
                ('contest', models.CharField(max_length=50, verbose_name='介绍')),
            ],
            options={
                'verbose_name_plural': '成员',
                'verbose_name': '成员',
            },
        ),
        migrations.CreateModel(
            name='Works',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=500, verbose_name='分类名称')),
            ],
            options={
                'verbose_name_plural': '分类',
                'verbose_name': '分类',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='works',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='blog.Works'),
        ),
        migrations.AddField(
            model_name='knowledge',
            name='works',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='blog.Works'),
        ),
        migrations.AddField(
            model_name='case',
            name='c_works',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='blog.Works'),
        ),
    ]
